version: '3'

volumes:
  pg_data:

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    networks:
      - doctor_network
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env

  flyway:
    image: flyway/flyway:11
    container_name: flyway
    depends_on:
      - postgres
    command: [
      "migrate",
      "-url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}",
      "-user=${POSTGRES_USER}",
      "-password=${POSTGRES_PASSWORD}"
    ]
    networks:
      - doctor_network
    volumes:
      - ./migrations:/flyway/sql
    env_file: .env

  backend:
    image: b0ev/doctor_aibolit
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - doctor_network
    volumes:
      - ./.env:/root/.env
    depends_on:
      - flyway

networks:
  doctor_network:
    driver: bridge
