name: workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test -v ./...

  migrate:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Flyway
      run: |
        curl -L -o flyway-commandline.tar.gz "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/11.1.0/flyway-commandline-11.1.0-linux-x64.tar.gz"
        
        if [ ! -s flyway-commandline.tar.gz ]; then
          echo "Error: Flyway archive download failed!"
          exit 1
        fi
        
        tar -xzf flyway-commandline.tar.gz
        sudo ln -s "$(pwd)/flyway-11.1.0/flyway" /usr/local/bin/flyway
        rm flyway-commandline.tar.gz

    - name: Run Flyway migrations
      env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        FLYWAY_URL: "jdbc:postgresql://${{secrets.POSTGRES_HOST}}:${{secrets.POSTGRES_PORT}}/${{secrets.POSTGRES_DB}}"
        FLYWAY_LOCATIONS: "filesystem:migrations"
      run: |
        flyway -url=$FLYWAY_URL -user=$POSTGRES_USER -password=$POSTGRES_PASSWORD -locations=$FLYWAY_LOCATIONS migrate
